### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by moda84** [LoneDev6/Issues-Wraith#103] opened 2023-06-23 13:42 UTC
[16:38:50] [Server thread/INFO]: [Wraith] Enabling Wraith v2.3.5b
[16:38:50] [Server thread/ERROR]: [Wraith] Error getting implementation for class dev.lone.wraith.NMS.Player.PlayerNMS - NMS v1_20_R1
[16:38:50] [Server thread/WARN]: java.lang.ClassNotFoundException: dev.lone.wraith.NMS.Player.impl.v1_20_R1
[16:38:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185)
[16:38:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152)
[16:38:50] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:38:50] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[16:38:50] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[16:38:50] [Server thread/WARN]: 	at Wraith_2.3.5b.jar//dev.lone.wraith.NMS.Nms.a(SourceFile:80)
[16:38:50] [Server thread/WARN]: 	at Wraith_2.3.5b.jar//dev.lone.wraith.NMS.Nms.a(SourceFile:60)
[16:38:50] [Server thread/WARN]: 	at Wraith_2.3.5b.jar//dev.lone.wraith.NMS.Player.PlayerNMS.<init>(SourceFile:28)
[16:38:50] [Server thread/WARN]: 	at Wraith_2.3.5b.jar//dev.lone.wraith.NMS.Player.PlayerNMS.a(SourceFile:22)
[16:38:50] [Server thread/WARN]: 	at Wraith_2.3.5b.jar//dev.lone.wraith.Main.onEnable(SourceFile:181)
[16:38:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[16:38:50] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[16:38:50] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[16:38:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[16:38:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:580)
[16:38:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:491)
[16:38:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[16:38:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440)
[16:38:50] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
[16:38:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
[16:38:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[16:38:50] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:38:50] [Server thread/INFO]: [Wraith] Disabling Wraith v2.3.5b
[16:38:50] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling Wraith v2.3.5b (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.lone.wraith.main.bU.ag()" because "dev.lone.wraith.Main.a" is null
	at dev.lone.wraith.Main.onDisable(SourceFile:429) ~[Wraith_2.3.5b.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at dev.lone.wraith.NMS.Nms.a(SourceFile:99) ~[Wraith_2.3.5b.jar:?]
	at dev.lone.wraith.NMS.Nms.a(SourceFile:60) ~[Wraith_2.3.5b.jar:?]
	at dev.lone.wraith.NMS.Player.PlayerNMS.<init>(SourceFile:28) ~[Wraith_2.3.5b.jar:?]
	at dev.lone.wraith.NMS.Player.PlayerNMS.a(SourceFile:22) ~[Wraith_2.3.5b.jar:?]
	at dev.lone.wraith.Main.onEnable(SourceFile:181) ~[Wraith_2.3.5b.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:580) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:491) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:38:50] [Server thread/ERROR]: [Wraith] Error getting implementation for class dev.lone.wraith.NMS.Server.ServerNMS - NMS v1_20_R1
[16:38:50] [Server thread/WARN]: java.lang.ClassNotFoundException: dev.lone.wraith.NMS.Server.impl.v1_20_R1
[16:38:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185)
[16:38:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152)
[16:38:50] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:38:50] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[16:38:50] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[16:38:50] [Server thread/WARN]: 	at Wraith_2.3.5b.jar//dev.lone.wraith.NMS.Nms.a(SourceFile:80)
[16:38:50] [Server thread/WARN]: 	at Wraith_2.3.5b.jar//dev.lone.wraith.NMS.Nms.a(SourceFile:60)
[16:38:50] [Server thread/WARN]: 	at Wraith_2.3.5b.jar//dev.lone.wraith.NMS.Server.ServerNMS.<init>(SourceFile:20)
[16:38:50] [Server thread/WARN]: 	at Wraith_2.3.5b.jar//dev.lone.wraith.NMS.Server.ServerNMS.a(SourceFile:14)
[16:38:50] [Server thread/WARN]: 	at Wraith_2.3.5b.jar//dev.lone.wraith.Main.onEnable(SourceFile:182)
[16:38:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[16:38:50] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[16:38:50] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[16:38:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[16:38:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:580)
[16:38:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:491)
[16:38:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[16:38:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440)
[16:38:50] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
[16:38:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
[16:38:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[16:38:50] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:38:50] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_20_R1! Trying to find NMS support
[16:38:50] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_20_R1' loaded!
[16:38:50] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[16:38:50] [Server thread/INFO]: ███████
[16:38:50] [Server thread/INFO]: ███████
[16:38:50] [Server thread/INFO]: ██▀██▀█ Wraith > haunts every hacker
[16:38:50] [Server thread/INFO]: ███████ Version: 2.3.5b
[16:38:50] [Server thread/INFO]: ███████
[16:38:50] [Server thread/ERROR]: Error occurred while enabling Wraith v2.3.5b (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register dev.lone.wraith.main.bU@13993781 while not enabled
	at io.papermc.paper.plugin.manager.PaperEventManager.registerEvents(PaperEventManager.java:80) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.registerEvents(PaperPluginManagerImpl.java:131) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:674) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at dev.lone.wraith.main.df.a(SourceFile:16) ~[Wraith_2.3.5b.jar:?]
	at dev.lone.wraith.main.bU.k(SourceFile:71) ~[Wraith_2.3.5b.jar:?]
	at dev.lone.wraith.main.bU.<init>(SourceFile:66) ~[Wraith_2.3.5b.jar:?]
	at dev.lone.wraith.Main.onEnable(SourceFile:322) ~[Wraith_2.3.5b.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:580) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:491) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LoneDev6** [comment] 2023-06-24 14:13
Duplicate of https://github.com/PluginBugs/Issues-Wraith/issues/102

**Closed as not planned by LoneDev6** 2023-06-24 14:13 UTC
Labels: duplicate
