### ISSUE TITLE
[BUG] little issue on login - only sometimes... reason unknown

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#100] opened 2023-04-12 08:36 UTC
**Describe the bug**
Sometimes when a player moves arround after login he get this error from wraith.
im not sure what the error wants to tell us..

**To Reproduce**
1. login and move a bit arround...
2. See error in console..

**Expected behavior**
no error in console...

**Screenshots**
![image](https://user-images.githubusercontent.com/12080017/231401411-49d0ef30-dae0-424b-87b5-74fc023c09ac.png)

**Info (please complete the following information):**
 - Server version: PaperMC 1.19.4 Build 503
 - Client version: Vanilla Java Edition 1.19.4
 - Plugin version: latest...* joiking*  Wraith_2.3.5  and LoneLibs_1.0.24

**Additional context**
Error - logpart from console
```
[09:43:29] [Timer-4/WARN]: Exception in thread "Timer-4" java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
[09:43:29] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.impl.v1_19_R3.a(SourceFile:29)
[09:43:29] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.Blocks.a(SourceFile:162)
[09:43:29] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.b(SourceFile:982)
[09:43:29] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.K(SourceFile:960)
[09:43:29] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.ai(SourceFile:168)
[09:43:29] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.bX.run(SourceFile:136)
[09:43:29] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[09:43:29] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
[09:43:29] [Timer-3/WARN]: Exception in thread "Timer-3" java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
[09:43:29] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.impl.v1_19_R3.a(SourceFile:29)
[09:43:29] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.Blocks.a(SourceFile:162)
[09:43:29] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.b(SourceFile:982)
[09:43:29] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.K(SourceFile:960)
[09:43:29] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.ai(SourceFile:168)
[09:43:29] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.bX.run(SourceFile:136)
[09:43:29] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[09:43:29] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
```

**Comment by CloudeLecaw** [comment] 2023-04-12 21:17
Today aggain after a user logged in

```
[23:13:16] [Server thread/INFO]: SecretMystery99[/89.1.209.165:20377] logged in with entity id 6757 at ([world]-891.5, 65.87500002384186, -2920.2)
[23:13:17] [Timer-4/WARN]: Exception in thread "Timer-4" java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
[23:13:17] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.impl.v1_19_R3.a(SourceFile:29)
[23:13:17] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.Blocks.a(SourceFile:162)
[23:13:17] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.b(SourceFile:982)
[23:13:17] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.K(SourceFile:960)
[23:13:17] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.ai(SourceFile:168)
[23:13:17] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.bX.run(SourceFile:136)
[23:13:17] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[23:13:17] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
[23:13:17] [Timer-3/WARN]: Exception in thread "Timer-3" java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
[23:13:17] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.impl.v1_19_R3.a(SourceFile:29)
[23:13:17] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.Blocks.a(SourceFile:162)
[23:13:17] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.b(SourceFile:982)
[23:13:17] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.K(SourceFile:960)
[23:13:17] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.ai(SourceFile:168)
[23:13:17] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.bX.run(SourceFile:136)
[23:13:17] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[23:13:17] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
```

might there is a reason for this? might little code chanes in 1.19.4? :3

**Comment by LoneDev6** [comment] 2023-05-11 13:24
Duplicate of https://github.com/PluginBugs/Issues-Wraith/issues/101

**Closed as not planned by LoneDev6** 2023-05-11 13:24 UTC
Labels: duplicate
