### ISSUE TITLE
[BUG] Plugin does not Load in 1.20.1

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#104] opened 2023-06-23 16:53 UTC
**Describe the bug**
The plugin does not load in 1.20.1

**To Reproduce**
1. Take current latest wraith and lonedev libs
2.take latest paper 1.20.1 build
3. start the server

**Expected behavior**
The plugin should load (and ork in best case).

**Info (please complete the following information):**
 - Server version: paper 1.20.1
 - Client version: vaniilia Client 1.20.1
 - Plugin version: None its not worthing with Wraith_2.3.5b

Well a simliar thing for 1.20 with wrong header and a little short text was postest here
https://github.com/PluginBugs/Issues-Wraith/issues/102

**Comment by LoneDev6** [comment] 2023-06-24 14:13
Duplicate of https://github.com/PluginBugs/Issues-Wraith/issues/102

**Closed as not planned by LoneDev6** 2023-06-24 14:13 UTC
Labels: duplicate
